
platform :ios, '13.0'

target 'FlashChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlashChat
  pod "Firebase/Auth"
  pod "Firebase/Firestore"
    
end
